### ISSUE TITLE
SVT : Eclipse latest : New Java Spring projects fail maven build 

### ISSUE THREAD

**Issue by mmulholl** [eclipse/codewind#1414]
**Codewind version:**   Codewind tech preview	0.6.0.v201912022032	
  codewind-pfe-amd64:latest
**OS:** Mac

**Che version:**
**IDE extension version:**
**IDE version:**
**Kubernetes cluster:**

**Description:**
Newly created Java Spring apps fail in maven build.
If I look at maven build logs for the project I just get: Waiting for server to send logs...

**Steps to reproduce:**
Create a new Java Spring project and wait for build to fail.

**Workaround:**

**Comment by eharris369** [comment]
Here is a pfe log for the failure: 
[logs.txt](https://github.com/eclipse/codewind/files/3933337/logs.txt)

**Comment by jagraj** [comment]
I also see same problem on Windows.

**Comment by ssh24** [comment]
Looks like `mvn` is not found from the logs
```
[91m[05/12/19 11:13:36 spring1] [ERROR][39m executeBuildScript : 399 | /scripts/spring-build.sh: line 21: mvn: command not found
```

**Comment by elsony** [comment]
It looks like docker build failed. Can you provide docker.build.log?

**Comment by elsony** [comment]
This section in the log looks suspicious as well:
[32m[05/12/19 11:13:36 /portal/routes/projects/remoteBind.route.js] [INFO][39m Project spring1 syncing with build container, projectRoot is /root/app
[91m[05/12/19 11:13:37 /portal/routes/projects/remoteBind.route.js] [ERROR][39m { Error: Command failed: docker cp /codewind-workspace/spring1/. undefined:/root/app
Error: No such container:path: undefined:/root

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
  killed: false,
  code: 1,
  signal: null,
  cmd:
   'docker cp /codewind-workspace/spring1/. undefined:/root/app',
  stdout: '',
  stderr: 'Error: No such container:path: undefined:/root\n' }
[91m[05/12/19 11:13:37 /portal/middleware/errorHandler.js] [ERROR][39m { error:
   { name: 'Error [ERR_HTTP_HEADERS_SENT]',
     message: 'Cannot set headers after they are sent to the client' } }
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:470:11)
    at ServerResponse.header (/portal/node_modules/express/lib/response.js:771:10)
    at ServerResponse.send (/portal/node_modules/express/lib/response.js:170:12)
    at handleErrors (/portal/middleware/errorHandler.js:8:26)
    at newFn (/portal/node_modules/express-async-errors/index.js:16:20)
    at Layer.handle_error (/portal/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/portal/node_modules/express/lib/router/index.js:315:13)
    at /portal/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/portal/node_modules/express/lib/router/index.js:335:12)
    at next (/portal/node_modules/express/lib/router/index.js:275:10)

**Comment by ssh24** [comment]
I saw that previously as well and have https://github.com/eclipse/codewind/issues/1029 opened for it

**Comment by elsony** [comment]
Can we get the docker build log?  Given mvn is missing, chances are there are some issues on pulling down maven during the docker build.

**Comment by eharris369** [comment]
[docker.build.log](https://github.com/eclipse/codewind/files/3940596/docker.build.log)

**Comment by ssh24** [comment]
I don't think docker build failed. Everything looks good on that log

**Comment by maysunfaisal** [comment]
cant seem to reproduce it on 0.7.0 latest

**Comment by rajivnathan** [comment]
From the pfe logs Erin posted I see

```
[32m[05/12/19 11:13:31 /portal/routes/projects/remoteBind.route.js] [INFO][39m Removing locally deleted files from project: spring1, ID: 448375b0-1750-11ea-a18c-57b302a87e0d - Dockerfile-build
```
```
[91m[05/12/19 11:13:32 spring1] [ERROR][39m executeBuildScript : 399 | cat: Dockerfile-build: No such file or directory
```

The Dockerfile-build is what adds maven to the image. It looks like the remoteBind code is removing the file before it's used. I'm guessing this is a timing issue. If the file is deleted before this line is called https://github.com/eclipse/codewind/blob/113231c2b7973976ed182066b7f0df73f45a7eb4/src/pfe/file-watcher/scripts/spring-container.sh#L483 then it'll result in this problem.

@eharris369 @mmulholl @jagraj If you check the `codewind-workspace` in pfe, is there a `Dockerfile-build` file in the spring project folder? (It will only be inside the pfe container, not on the host machine)

Based on this, think it should be moved to portal to investigate the remoteBind behaviour. Particularly, how to prevent deletion of files created by Turbine in the project folder within PFE's workspace.

**Comment by eharris369** [comment]
I do not see a `Dockerfile-build` file in the `codewind-workspace` project folder inside the codewind-pfe container.

**Comment by rajivnathan** [comment]
Created a PR for the spring template to have the file there by default. This should resolve the issue for projects created via our template (Microprofile has a Dockerfile-build as part of the project so we'd just be making it consistent with Microprofile). The file wasn't needed in the template in the past because Turbine would create the file in the project folder and that was mounted so the user would be aware of the file but now that the mount is gone we should really add it to the template.

I'll still move this issue over to portal to determine whether we're behaving correctly. Perhaps one thing we can try to do is prevent deletion of files while a build is running.

**Comment by malincoln** [comment]
@tobespc I see this is still in interative-dev backlog but will probably be moved shortly?

**Comment by tobespc** [comment]
I've merged the pr to the samples template, this should now be ok

**Comment by malincoln** [comment]
@mmulholl pls verify and close.  Thanks

**Comment by mmulholl** [comment]
Still seeing the same issue

**Comment by malincoln** [comment]
@tobespc heads-up.  Martin will add additional info.

**Comment by mmulholl** [comment]
I am still seeing the issue and and after working with @jagraj the problem seems to be that my codewind install in pulling the templates from the wrong location : 

https://raw.githubusercontent.com/kabanero-io/codewind-templates/master/devfiles/index.json

Do not know how this gets updated.

**Comment by tobespc** [comment]
you need to do a clean up first for this, I suspect you have install features left lying around in the codewind volume.  run this command (make sure codewind is not running)
`docker system prune --volumes`

**Comment by mmulholl** [comment]
@tobespec - Does this mean docker system prune is needed for 0.7.0 install?

**Comment by jagraj** [comment]
During 0.5.0 to 0.6.0 migration, users workspace migrated to docker volume and during migration codewind did not migrate to this new repo. If we remove the volume user has to bind all the projects again. We may still get into same issue when we add support for other cloud project types.

**Comment by malincoln** [comment]
@tobespc to investigate more on previous releases with SVT.  Also mentioned was a new issue for migration.

**Comment by mmulholl** [comment]
I uninstalled codewind, ran "docker volume rm codewind_cw-workspace", reinstalled codewind and now spring projects build OK.

**Comment by malincoln** [comment]
@mmulholl can this be closed now?

**Comment by mmulholl** [comment]
Closing, all is good now.
