### ISSUE TITLE
SVT: Unknown error during cwctl start prevents Codewind from starting

### ISSUE THREAD

**Issue by sujeilyfonseca** [eclipse/codewind#1739]
**Codewind version:** 0.8.0
**OS:** VM with Windows 10

**IDE extension version:** 0.8.0
**IDE version:** 1.41.1

**Description:** Unknown error during cwctl start prevents Codewind from starting. Eventually, error handling code deletes the docker-compose.yaml.

```
==> Run cwctl.exe --json install -t 0.8.0
<Output hidden>
==> End cwctl.exe --json install -t 0.8.0
==> Run cwctl.exe --json start -t 0.8.0
Debug: false
==> environment structure written to C:\Users\Administrator/.codewind/docker-compose.yaml
System architecture is:  amd64
Host operating system is:  windows
Attempting to find available port
2020/01/13 14:41:02 Unable to connect to port 10000 : listen tcp 127.0.0.1:10000: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.
Port 10001 Available
Please wait while containers initialize...  
{"error":"DOCKER_COMPOSE_START_ERROR","error_description":"exit status 1"}
==> End cwctl.exe --json start -t 0.8.0
```

<img width="384" alt="Screen Shot 2020-01-13 at 3 27 45 PM" src="https://user-images.githubusercontent.com/49531960/72289872-03431900-361a-11ea-913f-a9161c13e7bc.png">

@jagraj

**Comment by tetchel** [comment]
does `docker-compose --help` from a cmd/powershell work?

what if you run `cwctl.exe --json start -t 0.8.0` from cmd/powershell instead?

wondering if it is a PATH issue.

in any case, cwctl should probably be able to output a better error than `exit status 1`

**Comment by tetchel** [comment]
I see also that:
```
environment structure written to C:\Users\Administrator/.codewind/docker-compose.yaml
```

but that file doesn't exist. Perhaps cwctl should fail at that step, then. It's also interesting that that path contains both kinds of separators (`\` and `/`).

**Comment by liamchampton** [comment]
After having a look at this, we hard code the compose filepath to be `homeDir + "/.codewind/docker-compose.yaml"`.  We should change this to use `path/filepath` to make this an OS agnostic filepath as it seems this does not work on Windows. Should look something like this:
```
dockerComposeFile := filepath.FromSlash(homeDir + "/.codewind/docker-compose.yaml")
```

**Comment by mattcolegate** [comment]
Seems to be a weird debug string in debug output caused by https://github.com/eclipse/codewind-installer/commit/9e29dd05073f74990bb6bd8c9055d910bdc8bb9a#diff-e4d6dec85a05773800e99ed74bdf3c2dL46

`==> created file C:\Users\MattColegate\Desktop\GitRepos\mattcolegate\codewind/C:\Users\MattColegate/.codewind/docker-compose.yaml`

Otherwise it's working ok on my Windows 10 box so far - going to try using a terminal that's not so hot with Unix filepaths/commands

**Comment by mattcolegate** [comment]
/assign
/pipeline in progress

Unable to recreate locally, but have logged onto the remote box and determined that the issue is being caused during `docker compose up` - the CLI deletes the docker-compose.yaml if a problem is detected there, so that's why it can't be found. Will debug on target system.

**Comment by mattcolegate** [comment]
I altered cwctl to spit out docker-compose's sysout and syserr when it detects an error having run docker compose - this is what it told me:
```
PS C:\Users\Administrator\.codewind\0.8.0> .\cwctl-win.exe --json start -t 0.8.0
Debug: false
==> environment structure written to C:\Users\Administrator/.codewind/docker-compose.yaml
System architecture is:  amd64
Host operating system is:  windows
Attempting to find available port
2020/01/14 10:17:14 Unable to connect to port 10000 : listen tcp 127.0.0.1:10000: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.
Port 10001 Available
Please wait while containers initialize...
Creating codewind-performance ...
?[1Bting codewind-performance ... ?[31merror?[0m
ERROR: for codewind-performance  Cannot start service codewind-performance: b'driver failed programming external connectivity on endpoint codewind-performance (2172dc931082daf8234e0405e086bbf9c09804e060091c6640653f3bd0926472): Error starting userland proxy: listen tcp 127.0.0.1:9095: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.'

ERROR: for codewind-performance  Cannot start service codewind-performance: b'driver failed programming external connectivity on endpoint codewind-performance (2172dc931082daf8234e0405e086bbf9c09804e060091c6640653f3bd0926472): Error starting userland proxy: listen tcp 127.0.0.1:9095: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.'
Encountered errors while bringing up the project.
{"error":"DOCKER_COMPOSE_START_ERROR","error_description":"exit status 1"}
```

I've seen the 'one usage' errors before when docker fails to bring down a container cleanly on Windows - it leaves open processes behind that keep the sockets open, then when we try to re-use these sockets it can't do it. I've fixed it before by restarting the computer so all the processes definitely go away, although I've read of people being able to kill certain processes spawned by Docker to do it without a restart. I'm going to try the full restart as it's quicker.

**Comment by mattcolegate** [comment]
Restarting the computer successfully solved the problem.

```
PS C:\Users\Administrator\.codewind\0.8.0> .\cwctl-win.exe --json start -t 0.8.0
Debug: false
==> environment structure written to C:\Users\Administrator/.codewind/docker-compose.yaml
System architecture is:  amd64
Host operating system is:  windows
Attempting to find available port
Port 10000 Available
Please wait while containers initialize...
Recreating codewind-performance ...
?[1BCreating codewind-pfe           ... mdone?[0m
?[1BWaiting for Codewind to start.. ?[32mdone?[0m
.............
HTTP Response Status: 200 OK
Codewind successfully started on http://127.0.0.1:10000
PS C:\Users\Administrator\.codewind\0.8.0>
```

I will be adding the docker-compose sysout & syserr to the output from the CLI when such an error occurs in future as this would have sped up diagnosis.

In summation, problem lies with Docker processes keeping sockets open after problems stopping a container. Rebooting the system fixes the problem.

**Comment by sujeilyfonseca** [comment]
Thank you very much for working to solve this problem, @liamchampton and @mattcolegate!

I verified this issue on 01/14/2019. I still see the strange path:
`environment structure written to C:\Users\Administrator/.codewind/docker-compose.yaml`

However, I can now start Codewind successfully. I consider it would be good to fix the strange path so that it is consistent with the operating system format. However, since this problem was resolved and https://github.com/eclipse/codewind/issues/1747 will address an improvement to help with a future diagnosis, I will proceed to close this GitHub issue.

**Comment by sujeilyfonseca** [comment]
I reopened this issue since @jagraj encountered this problem again.

**Comment by jagraj** [comment]
I got into this problem again on my windows machine. I installed latest 0.8.0 build after uninstalling my codewind plugin on Eclipse. I got into same problem when starting codewind. 

```
!ENTRY org.eclipse.egit.ui 2 0 2020-01-17 10:47:10.807
!MESSAGE Warning: The environment variable HOME is not set. The following directory will be used to store the Git
user global configuration and to define the default location to store repositories: 'C:\Users\Administrator'. If this is
not correct please set the HOME environment variable and restart Eclipse. Otherwise Git for Windows and
EGit might behave differently since they see different configuration options.
This warning can be switched off on the Team > Git > Confirmations and Warnings preference page.
!ENTRY org.eclipse.codewind.core 4 0 2020-01-17 10:51:28.275
!MESSAGE [ERROR CodewindInstall.getErrorStatus:496] Installer failed with return code: 1, output: Debug: false
==> environment structure written to C:\Users\Administrator/.codewind/docker-compose.yaml
System architecture is:  amd64
Host operating system is:  windows
Attempting to find available port
Port 10000 Available
Please wait while containers initialize...  
, error: time="2020-01-17T10:51:27-05:00" level=error msg="exit status 1"
```

**Comment by jagraj** [comment]
We are not getting enough trace information here when this is failing. We have not seen this kind of behavior in 0.7.0 release and also there are no updates to docker from past 2 months.

**Comment by jagraj** [comment]
Making this issue as "stopship"

/priority stopship

**Comment by malincoln** [comment]
@mattcolegate @tobespc  ^^^ this one has been reopened.
Moving back to new

**Comment by liamchampton** [comment]
> We are not getting enough trace information here when this is failing. We have not seen this kind of behavior in 0.7.0 release and also there are no updates to docker from past 2 months.

There is an issue open to rectify the lack of output given by `docker-compose` https://github.com/eclipse/codewind/issues/1747

This also looks like a different issue as the log states the `HOME` envar is not set. This variable is used in `docker-compose`.

**Comment by jagraj** [comment]
Thanks @liamchampton getting into web-ex and debugging this problem further in my windows machine. We both agree that trace is missing for the failure there is no way to find out root cause of this failure.

**Comment by mattcolegate** [comment]
@jagraj did the issue clear once you'd restarted your Windows machine or does that workaround not work any more?

**Comment by jagraj** [comment]
@mattcolegate 
I did not restart windows machine. This was not the behavior I have seen in the past releases. Couple of days back I restarted WIndows machine for Symantec Endpoint Protection install and that might have fixed the problem. I thought there was fix delivered to address this problem. Rebooting Windows machine for codewind install is not good user experience.

**Comment by tobespc** [comment]
Can we try a vanilla install of 0.8.0 to see if that works ? (might help with recreation scenario)

**Comment by tobespc** [comment]
This could well be the same issue as https://github.com/eclipse/codewind/issues/1558

**Comment by mattcolegate** [comment]
Hadn't realized this was an upgrade issue, so with @liamchampton's help we went through several upgrades from 0.7.0 to 0.8.0 on my Win 10 laptop using installers built from the 0.7.0 and 0.8.0 branches. All upgrades completed successfully. I still believe this is an environmental issue on the test machine.
Checked versions of Docker installed on test machine and my laptop - they match.
Have raised https://github.com/eclipse/codewind-installer/pull/340 to put extra logging in place for this error scenario.
Attempted to do a straight 0.8.0 install from nothing as @tobespc asked, but got booted off test machine by someone else logging in - to be fair, it was 9am where the test team were!
Will resume attempt to do a straight install on the test machine first thing tomorrow if one has not been attempted by @jagraj or @sujeilyfonseca before then.

**Comment by mattcolegate** [comment]
Could someone with the power to please also change the Issue title - problem is not being caused by lack of a docker-compose.yaml, it's the reverse - the error handling code deletes the docker-compose.yaml: https://github.com/eclipse/codewind-installer/blob/master/pkg/utils/docker.go#L136

**Comment by mattcolegate** [comment]
@sujeilyfonseca :-) So I think the title should be 'SVT: Unknown error during cwctl start prevents Codewind from starting'. The removal of the docker-compose.yaml file is incidental. 

Though this raises a good point - is the view of the SVT team that the docker-compose.yaml should not be deleted when errors occur? @liamchampton can you shed insight on why it was designed this way? @tetchel any thoughts?

**Comment by jagraj** [comment]
I just hit this problem again on one of my other Windows VM where I am trying to reproduce this problem. Here are the steps that I followed to reproduce this problem. 

1. Install Codewind 0.7.0 
2. Create default template projects (Go, Nodejs) , Appsody (Spring Kotlin, Eclipse Microprofile).
3. After successful build and running of these projects. Upgrade Codewind 0.7.0 to 0.8.0
4. Upgrade completed successfully and all my projects built and running.
5. Uninstall codewind and eclipse plugin.
6. Install 0.8.0 Codewind again.
7. Start codewind and it fails to start.

 ```There was a problem trying to start Codewind: time="2020-01-20T16:33:51-05:00" level=error msg="exit status 1"```

![Screen Shot 2020-01-20 at 5 12 54 PM](https://user-images.githubusercontent.com/713849/72760862-29cbfb80-3ba8-11ea-8c12-acec313fd1d5.png)

**Comment by mattcolegate** [comment]
@jagraj can you expand step 3 into a series of easy to follow steps so that I can truly do what you are doing please?

**Comment by liamchampton** [comment]
@mattcolegate the reason it was designed to delete the `docker-compose.yaml` file is so that it doesn't leave artifacts behind if an error occurs. The contents of the `.yaml` file can be spat out to the terminal by adding `-d` onto the end of the start command so at the time we didnt see a reason for keeping the file. The reason Codewind doesn't start here isn't because the file doesn't exist as it is created and attempted to make use of, but it fails and then gets cleaned up. Since we have hit this issue there are two clear outcomes:
1. We need better error logging for this scenario
2. We should keep the `docker-compose.yaml` file and only remove it when the `./codewind` directory is removed (this may help us debug any other future issues regarding the file)

**Comment by tobespc** [comment]
Can I get some clarification on the recreation steps please.    For all these steps, are they all being done by only using the eclipse or vscode codewind plugins or, is it a mixture of also running the cwctl manually?

We are only using the eclipse/vscode plugins in order to try an recreate which is how a user would be doing this.

**Comment by jagraj** [comment]
@tobespc 
I am running with Eclipse plugin and Sujeily got into this issue with VSCode plugin. We are not running all the steps using plugins and not from "cwctl" CLI.

**Comment by sujeilyfonseca** [comment]
I agree with @jagraj steps. I was able to reproduce this problem several times only using Codewind for VS Code on Windows:

1. Install and start Codewind 0.7.0
2. Create some projects
3. Wait for the applications to be in "Running" state
4. Upgrade to Codewind 0.8.0
5. Uninstall plugin and remove images belonging to Codewind for VS Code
6. Install and start Codewind 0.8.0 
7. Failure will appear

**Comment by mattcolegate** [comment]
@jagraj took me through a recreate scenario a couple of hours ago and was unable to recreate. We agreed to remove stopship tag from issue, try and get eclipse/codewind-installer#340 into 0.8.0 stream to at least log the problem if it occurs for the customer, and continue investigation in 0.9.0 if a reliable recreation method could be found.

**Comment by tobespc** [comment]
If this is not a stop ship then I don't think we should add anything to the 0.8.0 codebase.   Any last minute change has the potential to cause disruption

**Comment by malincoln** [comment]
let's discuss in a few minutes

**Comment by malincoln** [comment]
agreed to add fix in 0.9.0

**Comment by mattcolegate** [comment]
https://github.com/eclipse/codewind-installer/pull/340 is now merged, so I'm closing this issue. If this problem is encountered again, a new issue can be raised with the improved logging pointing more clearly at the cause.

**Comment by jgwest** [comment]
@mattcolegate: Unable to locate pipeline with name: `closed`

**Comment by mattcolegate** [comment]
@tobespc Please close this issue at your earliest convenience.
