### ISSUE TITLE
SVT: Error toggling logs: Response code 500 (Internal Server Error)

### ISSUE THREAD

**Issue by sujeilyfonseca** [eclipse/codewind#3062]
**Codewind version:** 0.13.0
**OS:** VM with Windows 10

**IDE extension version:** 0.13.0
**IDE version:** Code 1.45.0

**Description:** Error toggling logs: Response code 500 (Internal Server Error)

<img width="1677" alt="Screen Shot 2020-05-28 at 1 29 03 PM" src="https://user-images.githubusercontent.com/49531960/83175392-cfa8ed00-a0e9-11ea-8735-07d7c95489f5.png">

<img width="1677" alt="Screen Shot 2020-05-28 at 1 44 01 PM" src="https://user-images.githubusercontent.com/49531960/83175332-bb64f000-a0e9-11ea-9d72-5bb0e7984ae8.png">

<img width="1676" alt="Screen Shot 2020-05-28 at 1 44 35 PM" src="https://user-images.githubusercontent.com/49531960/83175314-b43de200-a0e9-11ea-8472-26427909b76e.png">

**Logs:** 
[codewind.log](https://github.com/eclipse/codewind/files/4697370/codewind.log)
[codewind-pfe.txt](https://github.com/eclipse/codewind/files/4697332/codewind-pfe.txt)

@jagraj

**Comment by jgwest** [comment]
Guessing this is `area/portal` based on 
```
[28/05/20 17:23:54 /portal/routes/projects/bind.route.js] [ERROR] Project creation failed for project microprofile. Error: RangeError: Maximum call stack size exceeded
    at Function.[Symbol.hasInstance] (<anonymous>)
    at Function.isBuffer (buffer.js:430:12)
    at hasBinary (/portal/node_modules/has-binary2/index.js:44:66)
    at hasBinary (/portal/node_modules/has-binary2/index.js:58:59)
    at hasBinary (/portal/node_modules/has-binary2/index.js:58:59)
    at hasBinary (/portal/node_modules/has-binary2/index.js:58:59)
    at hasBinary (/portal/node_modules/has-binary2/index.js:58:59)
    at hasBinary (/portal/node_modules/has-binary2/index.js:58:59)
    at hasBinary (/portal/node_modules/has-binary2/index.js:58:59)
    at hasBinary (/portal/node_modules/has-binary2/index.js:58:59)
```

**Comment by hhellyer** [comment]
@jgwest - I think that stack overflow is from earlier on during project creation. I've pushed a fix for that here: https://github.com/eclipse/codewind/pull/3073

**Comment by hhellyer** [comment]
@sujeilyfonseca - I can't reproduce this but I'm adding some extra null checks. It looks like you were running on Windows though and we do handle some log files differently on Windows. I'll put the null check fixes in but after that could you check whether you actually get the logs you expect? (As well as whether the exception is fixed!)

**Comment by sujeilyfonseca** [comment]
Thanks for working to address this issue, @hhellyer! I will verify if all logs are provided once you merge your fixes.

I have also seen this error on other platforms. Here is an example with Eclipse Che and Codewind 0.13.0:

<img width="1594" alt="Screen Shot 2020-05-30 at 8 37 56 PM" src="https://user-images.githubusercontent.com/49531960/83361713-22d4a700-a359-11ea-9524-dd000becd6a2.png">

[codewind-workspace4qg812hdkzppar4r-6679dcff45-fn6gm.txt](https://github.com/eclipse/codewind/files/4708348/codewind-workspace4qg812hdkzppar4r-6679dcff45-fn6gm.txt)
[theia-ideicj.txt](https://github.com/eclipse/codewind/files/4708349/theia-ideicj.txt)

**Comment by mattcolegate** [comment]
Grabbing this for a bit to see if I can reproduce on Windows now Howard's fix has merged
/assign
/pipeline in progress

**Comment by mattcolegate** [comment]
Hi @sujeilyfonseca,
I've attempted to recreate this issue today using the latest code with Howard's fix in it, and while I've not been able to get the appsody projects to start up, I haven't had an error about toggling logs and I have been able to view appsody-liberty's appsody.log showing the maven build and test. Please can you verify that this issue is still occuring?
/pipeline verify

**Comment by hhellyer** [comment]
@sujeilyfonseca - The issue wasn't marked as stop ship so the fixes didn't go into 0.13.0.

I did raise PR's for 0.13.0 but since it wasn't stop ship the decision was made not to merge and they were closed rather than merged, I'm sorry if that caused confusion.

**Comment by sujeilyfonseca** [comment]
Thank you for working to solve this issue!

I verified this issue with the latest Codewind 0.14.0, and I no longer reproduce the problem.
